name: Gradle
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * * # daily
jobs:
  gradle-rc:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 21

        - name: Change wrapper permissions
          run: chmod +x ./gradlew

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4
    
        - name: Execute Gradle build
          run: ./gradlew build
